2024-09-11 14:49:29,000 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:49:29,002 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:51:54,222 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:51:54,222 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:51:54,558 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:51:54,558 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:51:54,893 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:51:54,893 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:51:55,220 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:51:55,220 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:51:55,544 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:51:55,544 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:53:01,696 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:53:01,697 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:53:06,062 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:53:06,062 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:53:11,379 ERROR: Unhandled exception [in /home/tingchieh/Documents/flask-study/app/tasks.py:64]
Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.12/smtplib.py", line 891, in sendmail
    (code, resp) = self.data(msg)
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 580, in data
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/app/tasks.py", line 54, in export_posts
    send_email(
  File "/home/tingchieh/Documents/flask-study/app/email.py", line 38, in send_email
    mail.send(msg)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.12/smtplib.py", line 993, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2024-09-11 14:58:16,618 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:58:16,618 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:58:22,642 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 14:58:22,642 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 14:58:27,943 ERROR: Unhandled exception [in /home/tingchieh/Documents/flask-study/app/tasks.py:64]
Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.12/smtplib.py", line 891, in sendmail
    (code, resp) = self.data(msg)
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 580, in data
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/app/tasks.py", line 54, in export_posts
    send_email(
  File "/home/tingchieh/Documents/flask-study/app/email.py", line 45, in send_email
    mail.send(msg)
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.12/smtplib.py", line 993, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2024-09-11 15:01:50,781 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 15:01:50,781 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 15:58:25,671 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 15:58:25,671 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
